name: ci-golang-workflow
# on: [push]
on: 
  pull_request:
    branches:
      - develop


jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/actions/checkout
      #https://github.com/actions/setup-go
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
