name: ci-golang-workflow
# on: [push]
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go: ["1.14", "1.15"]
    steps:
      #https://github.com/actions/checkout
      #https://github.com/actions/setup-go
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # go-version: ${{ matrix.go }}
            go-version: 1.15
      - run: go test
      - run: go run math.go

# Gerando o build
# https://github.com/marketplace/actions/build-and-push-docker-images
# https://github.com/docker/setup-qemu-action
# https://github.com/docker/setup-buildx-action
      # fazer um setup do docker para ele conseguir funcionar em diversar arquiteturas
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3
      # para conseguir fazer o build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

# subindo a imagem para o dockerHub, para adicionar a secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
        # para adicionar a secrets você precisa ir no git hub e adicionar
        # Settings / 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

# vai fazer o build and push 
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joseaugustoalmeida/integracao_continua2:latest
      
